<?php
namespace app\Controllers\IM;

/**
 * Created by PhpStorm.
 * User: ming123jew
 * Date: 2018-5-8
 * Time: 14:31
 */
class Index extends Base{

    public function initialization($controller_name, $method_name)
    {
        parent::initialization($controller_name, $method_name); // TODO: Change the autogenerated stub
    }


    public function http_index(){
        parent::webOrApp(function (){
            $template = $this->loader->view('app::IM/index');
            $this->http_output->end($template->render(['data'=>$this->TemplateData,'message'=>'']));
        });
    }


}