<?php
/**
 * Created by PhpStorm.
 * User: ming123jew
 * Date: 2017-12-28
 * Time: 14:55
 */
namespace app\Controllers\IM;

use app\Models\Data\ImHistoryLogModel;
use app\Models\Data\ImHistoryModel;
use app\Process\MyProcess;
use Server\Components\Event\EventDispatcher;
use Server\Components\Process\ProcessManager;
use Server\Memory\Cache;
use app\Controllers\BaseController;


class Ws extends BaseController{
    protected $Map;
    protected function initialization($controller_name, $method_name)
    {
        parent::initialization($controller_name, $method_name);
        $configs = get_instance()->config;
        $configs_config = $configs['config'];
        //print_r($configs_config);
        //print_r($this->ControllerName);
        //print_r($this->MethodName);
        $this->HtmlUrl = $configs_config[$configs_config['active']]['home']['static_url'];

        parent::templateData('HTML_URL',$this->HtmlUrl);
        unset($configs,$configs_config);
    }

    public function connect()
    {
        //绑定用户id
        $this->bindUid($this->client_data->uid);

        //发送通知用户我上线了

        //查找历史信息
        $this->Model['ImHistoryLogModel'] = $this->loader->model(ImHistoryLogModel::class,$this);
        if($this->client_data->uid){
            $this->Data['ImHistoryLogModel'] = yield $this->Model['ImHistoryLogModel']->getByUid( intval($this->client_data->uid) );
        }else{
            $this->Data['ImHistoryLogModel'] = [];
        }
        $this->send(['type' => 'welcome', 'id' => $this->client_data->uid,'fd'=>$this->fd,'history'=>$this->Data['ImHistoryLogModel']]);
    }

    public function sendData(){
        //检测是不是好友


        //获取接收uid是否在线
        $this->Data['isOnLine'] = yield get_instance()->coroutineUidIsOnline($this->client_data->message->to->id);
        if($this->Data['isOnLine']){
            $this->Data['status'] = 1;
        }else{
            $this->Data['status'] = 0;
        }

        //记录到数据库
        $this->Model['ImHistoryModel'] = $this->loader->model(ImHistoryModel::class,$this);
        $intoColumns = ['type','content','create_time','sender_uid','receiver_uid','status'];
        $intoValues = [
            $this->client_data->message->to->type,
            json_encode(  ['mine'=>(array)$this->client_data->message->mine,'to'=>(array)$this->client_data->message->to]  ),
            time(),
            $this->client_data->message->mine->id,
            $this->client_data->message->to->id,
            $this->Data['status']
        ];
        $this->Data['ImHistoryModel'] = yield $this->Model['ImHistoryModel']->insertMultiple($intoColumns,$intoValues);
        unset($intoColumns,$intoValues);
        $this->client_data->message->mine->type = $this->client_data->message->to->type;

        //var_dump($this->Data['isOnLine']);
        if($this->Data['isOnLine']){
            $this->sendToUid($this->client_data->message->to->id,['type'=>'sendData','data'=>$this->client_data->message->mine]);
        }
        //$this->send(['type' => 'sendData', 'message' => $this->Data['client_data'][$this->fd],'fd'=>$this->fd]);
    }


    public function historyData(){
        $this->Model['ImHistoryLogModel'] = $this->loader->model(ImHistoryLogModel::class,$this);
        //删除之前所有记录
        yield $this->Model['ImHistoryLogModel']->deleteByUid($this->client_data->uid);
        //记录到数据库
        $intoColumns = ['content','create_time','uid'];
        $intoValues = [
            $this->client_data->message,
            time(),
            $this->client_data->uid
        ];
        $this->Model['ImHistoryLogModel'] = yield $this->Model['ImHistoryLogModel']->insertMultiple($intoColumns,$intoValues);
        unset($intoColumns,$intoValues);
    }

    public function close($autoDestroy = true)
    {
        //发送通知，我下线了。。

        parent::close($autoDestroy); // TODO: Change the autogenerated stub

    }
}