<?php
/**
 * Created by PhpStorm.
 * User: zhangjincheng
 * Date: 16-7-15
 * Time: 下午1:44
 */

namespace app\Models\Data;


use Server\CoreBase\Model;


class BaseModel extends Model
{
    public $config;
    public $prefix;
    public $mysql_pool_builder;

    public function initialization(&$context)
    {
        $this->db = $this->mysql_pool->dbQueryBuilder;
        parent::initialization($context); // TODO: Change the autogenerated stub
        $this->config = get_instance()->config;
        $mysqlconfig = $this->config['mysql'];
        $this->prefix = $mysqlconfig[$mysqlconfig['active']]['prefix'];
    }

    /**
     * @return \Server\Asyn\Mysql\Miner
     */
    public function db(){
        return $this->mysql_pool->dbQueryBuilder;
    }

    public function table($tableName){
        return $this->prefix.$tableName;
    }

    public function test()
    {
        return   $this->prefix;
    }
}