<?php
/**
 * Created by PhpStorm.
 * User: ming123jew
 * Date: 2018-4-25
 * Time: 16:21
 */

namespace app\Controllers\Spider;


use Server\Asyn\HttpClient\HttpClient;


class AnalyseUrl extends Base {

    /**
     * 任务是否完成
     * @var bool
     */
    protected $isComplete = false;


    public function initialization($controller_name, $method_name)
    {
        parent::initialization($controller_name, $method_name); // TODO: Change the autogenerated stub
    }

    public function handle($class,string $s,...$argv){
        call_user_func(array($class,$s),...$argv);
    }

    //获取连接
    public function getUrlList(...$argv){
        $list[] = 'www.baidu.com';
        $list[] = 'www.sougou.com';
        print_r($argv[0]);

        $ip = self::_ip();


        $b = self::_http($argv[0],self::_agent());
        $this->SimpleHtmlDom->load($b);
       
        $a =   $this->SimpleHtmlDom->find('<script>');

        print_r($a);
    }

    private function _http($url,$agent)
    {
        $ch = curl_init($url);
        $options = [
            CURLOPT_USERAGENT => $agent,
            CURLOPT_REFERER => $this->referer,
        ];
        curl_setopt_array($ch, $options);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_BINARYTRANSFER, true);
        curl_setopt($ch, CURLOPT_TIMEOUT, 60);
        $output = curl_exec($ch);
        return $output;
    }


    public function getUrlContent(){
        print_r("yes");
    }

    public function getBody(){

    }
    public function getTitle(){

    }
    public function getDesc(){

    }
}


