<?php

namespace app\Controllers\Spider;

use Server\Components\Event\EventDispatcher;

/**
 * Created by PhpStorm.
 * User: ming123jew
 * Date: 17-09-14
 * Time: am09:51
 */
class Webpage extends Base
{



    public function initialization($controller_name, $method_name)
    {
        parent::initialization($controller_name, $method_name); // TODO: Change the autogenerated stub
        /** @var 初始化curl信息 */
        $this->header = $this->agent[rand(0, count($this->agent) - 1)];
        $this->referer = empty($referer) ? 'http://weixin.sogou.com/' : $referer;
        $this->host = empty($host) ? 'weixin.sogou.com' : $host;
        /** @var 处理微信图片的防盗链 */
        //$this->antiLeech = 'http://'.$_SERVER['SERVER_NAME'].'/admin.php/tool/wechat-img?url=';
        $this->antiLeech = '';
    }


    public function http_get_url()
    {
        $gzh = $this->http_input->postGet('wx');
        $ip= self::_ip();
        //$this->WeixinSougouHttpClient = get_instance()->getAsynPool('WeixinSougouHttpClient');
        $response = yield $this->WeixinSougouHttpClient->httpClient
            ->addHeader('CURLOPT_USERAGENT',self::_agent())
            ->addHeader('CLIENT-IP',$ip)
            ->addHeader('X-FORWARDED-FOR',$ip)
            ->addHeader('CURLOPT_REFERER',$this->referer)
            ->coroutineExecute("/weixin?type=1&query={$gzh}&ie=utf8&_sug_=y&_sug_type_=1");
        //print_r($this->WeixinSougouHttpClient->httpClient->toArray());
        //print_r($response);

        $this->SimpleHtmlDom->load($response['body']);
        //sogou_vr_11002301_box_0 标识
        $url = self::_htmlTransform( $this->SimpleHtmlDom->find('li[id=sogou_vr_11002301_box_0]',0)->find('a',0)->href );

        //投递一个任务
        $channel = $this->AMQPClent->channel();
        $msgBody = json_encode(["url" => $url,'callBackClass'=>'AnalyseUrl','action'=>'getUrlList']);
        $this->AMQPMessage->setBody($msgBody);
        //$msg = new AMQPMessage($this->AMQPMessage, ['content_type' => 'text/plain', 'delivery_mode' => 2]); //生成消息  //, ['content_type' => 'text/plain', 'delivery_mode' => 2]
        $channel->basic_publish($this->AMQPMessage,$this->AMQPMessage_exchange); //推送消息到某个交换机
        $channel->close();
        parent::httpOutputTis($url);
    }


    private function _http($url)
    {
        $ch = curl_init($url);
        $options = [
            CURLOPT_USERAGENT => $this->agent,
            CURLOPT_REFERER => $this->referer,
        ];
        curl_setopt_array($ch, $options);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($ch, CURLOPT_BINARYTRANSFER, true);
        curl_setopt($ch, CURLOPT_TIMEOUT, 60);
        $output = curl_exec($ch);
        return $output;
    }


    /**
     * 事件处理
     */
    public function http_getEvent()
    {

        $data = yield EventDispatcher::getInstance()->addOnceCoroutine('unlock')->setTimeout(1000);
        //这里会等待事件到达，或者超时
        $this->http_output->end($data);
    }

    public function http_sendEvent()
    {
        EventDispatcher::getInstance()->dispatch('unlock', 'hello block');
        $this->http_output->end('ok');
    }

}