<?php
/**
 * Created by PhpStorm.
 * User: ming123jew
 * Date: 2018-3-22
 * Time: 18:04
 */

namespace app\Models\Business;
use Server\CoreBase\Model;

class BaseBusiness extends Model
{
    public function initialization(&$context)
    {
        parent::initialization($context); // TODO: Change the autogenerated stub
    }
}