<?php
namespace app\Models\Task;
use app\Models\Data\BaseModel;
use app\Process\MyProcess;
use Server\Components\Consul\ConsulHelp;
use Server\Components\Process\ProcessManager;

/**
 * 使用task_name将会调用Task，使用model_name将会调用Model，Task是同步阻塞，Model是异步非阻塞
 * 使用Task有很多限制，如果是长耗时任务可以使用自定义进程，通过TimerTask.php配置调用Model，在Model里面通过进程间通讯API调用自定义进程
 * Created by PhpStorm.
 * User: ming123jew
 * Date: 2018-3-28
 * Time: 10:26
 */
class CacheTask extends BaseModel
{
    public function initialization(&$context)
    {
        parent::initialization($context); // TODO: Change the autogenerated stub
    }

    public function check(){

        //访问MyProcess进程getData方法
        $data = yield  ProcessManager::getInstance()->getRpcCall(MyProcess::class)->getData();
        print_r($data);
        return "ticker";
    }
}