<?php
/**
 * Created by PhpStorm.
 * User: ming123jew
 * Date: 2018-4-28
 * Time: 10:55
 */

namespace app\Models\Task;


use app\Models\Data\BaseModel;
use Server\Components\CatCache\TimerCallBack;

class SpiderTimerCallBack extends BaseModel
{

    public function initialization(&$context)
    {
        parent::initialization($context); // TODO: Change the autogenerated stub
    }

    public function Test($value,$token){
        var_dump($value,$token);

        //TimerCallBack::ack($token);
    }
}